name: mlops-example-pipeline

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup container for training
        uses: addnab/docker-run-action@v3
        with:
          image: dvcorg/cml-py3:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            pip install -r requirements.txt
            python src/pipelines/classification_pipeline.py