name: mlops-example-pipeline
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://iterativeai/cml:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python src/pipelines/classification_pipeline.py
